### ISSUE TITLE
ubuntu: lzma not avalable

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-data#2]
evan after installing lzma lib-dev it says lzma not available.

however xz is at /usr/bin/xz

lzma is equivalent to xz --format=lzma.

xz --compress  is compress
xz --decompress is decompress

**Comment by laszewsk** [comment]
also looks like that xz does not work on directories but files only? Is this correct?

**Comment by laszewsk** [comment]
======================================================================
cms data compress README.md a.xzdata compress README.md a.xz

# ----------------------------------------------------------------------
# arguments
# ----------------------------------------------------------------------
# 52:do_data ./cloudmesh/data/command/data.py
# ----------------------------------------------------------------------
# {'--': False,
#  '--algorithm': 'xz',
#  '--benchmark': False,
#  '--force': False,
#  '--level': None,
#  '--native': False,
#  '--sepopts': False,
#  'DESTINATION': None,
#  'FILE': 'README.md',
#  'LOCATION': 'a.xz',
#  'algorithm': 'xz',
#  'benchmark': False,
#  'compress': True,
#  'csv': None,
#  'file': None,
#  'force': False,
#  'info': False,
#  'level': None,
#  'native': False,
#  'sepopts': False,
#  'uncompress': False}
# ----------------------------------------------------------------------

ERROR: executing command 'data compress README.md a.xz'
======================================================================
lzma module is not available
lzma module is not available
Traceback (most recent call last):
  File "/home/machine/Desktop/cm/cloudmesh-cmd5/cloudmesh/shell/shell.py", line 1093, in main
    stop = cmd.onecmd(command)
  File "/home/machine/Desktop/cm/cloudmesh-cmd5/cloudmesh/shell/shell.py", line 421, in onecmd
    return func(arg)
  File "/home/machine/Desktop/cm/cloudmesh-cmd5/cloudmesh/shell/command.py", line 111, in new
    func(instance, args, arguments)
  File "/home/machine/Desktop/cm/cloudmesh-data/cloudmesh/data/command/data.py", line 62, in do_data
    worker.compress(src=arguments.LOCATION,
  File "/home/machine/Desktop/cm/cloudmesh-data/cloudmesh/data/data.py", line 187, in compress
    self._python_compress_dir(src, out=out, level=level)
  File "/home/machine/Desktop/cm/cloudmesh-data/cloudmesh/data/data.py", line 297, in _python_compress_dir
    with tarfile.open(out, **taropts) as tf:
  File "/usr/local/lib/python3.10/tarfile.py", line 1633, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/local/lib/python3.10/tarfile.py", line 1737, in xzopen
    raise CompressionError("lzma module is not available") from None
tarfile.CompressionError: lzma module is not available

======================================================================

**Comment by laszewsk** [comment]
we default to native at that time
